//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientTemprateur.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcultemp", ReplyAction="*")]
        clientTemprateur.ServiceReference1.CalcultempResponse Calcultemp(clientTemprateur.ServiceReference1.CalcultempRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcultemp", ReplyAction="*")]
        System.Threading.Tasks.Task<clientTemprateur.ServiceReference1.CalcultempResponse> CalcultempAsync(clientTemprateur.ServiceReference1.CalcultempRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcultempRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calcultemp", Namespace="http://tempuri.org/", Order=0)]
        public clientTemprateur.ServiceReference1.CalcultempRequestBody Body;
        
        public CalcultempRequest() {
        }
        
        public CalcultempRequest(clientTemprateur.ServiceReference1.CalcultempRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcultempRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double a;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public CalcultempRequestBody() {
        }
        
        public CalcultempRequestBody(double a, string type) {
            this.a = a;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcultempResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcultempResponse", Namespace="http://tempuri.org/", Order=0)]
        public clientTemprateur.ServiceReference1.CalcultempResponseBody Body;
        
        public CalcultempResponse() {
        }
        
        public CalcultempResponse(clientTemprateur.ServiceReference1.CalcultempResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcultempResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalcultempResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public CalcultempResponseBody() {
        }
        
        public CalcultempResponseBody(double CalcultempResult, string msg) {
            this.CalcultempResult = CalcultempResult;
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : clientTemprateur.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<clientTemprateur.ServiceReference1.WebService1Soap>, clientTemprateur.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientTemprateur.ServiceReference1.CalcultempResponse clientTemprateur.ServiceReference1.WebService1Soap.Calcultemp(clientTemprateur.ServiceReference1.CalcultempRequest request) {
            return base.Channel.Calcultemp(request);
        }
        
        public double Calcultemp(double a, string type, out string msg) {
            clientTemprateur.ServiceReference1.CalcultempRequest inValue = new clientTemprateur.ServiceReference1.CalcultempRequest();
            inValue.Body = new clientTemprateur.ServiceReference1.CalcultempRequestBody();
            inValue.Body.a = a;
            inValue.Body.type = type;
            clientTemprateur.ServiceReference1.CalcultempResponse retVal = ((clientTemprateur.ServiceReference1.WebService1Soap)(this)).Calcultemp(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.CalcultempResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clientTemprateur.ServiceReference1.CalcultempResponse> clientTemprateur.ServiceReference1.WebService1Soap.CalcultempAsync(clientTemprateur.ServiceReference1.CalcultempRequest request) {
            return base.Channel.CalcultempAsync(request);
        }
        
        public System.Threading.Tasks.Task<clientTemprateur.ServiceReference1.CalcultempResponse> CalcultempAsync(double a, string type) {
            clientTemprateur.ServiceReference1.CalcultempRequest inValue = new clientTemprateur.ServiceReference1.CalcultempRequest();
            inValue.Body = new clientTemprateur.ServiceReference1.CalcultempRequestBody();
            inValue.Body.a = a;
            inValue.Body.type = type;
            return ((clientTemprateur.ServiceReference1.WebService1Soap)(this)).CalcultempAsync(inValue);
        }
    }
}
