//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cLIENTwEBSERVICEcSHARP.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldResponse HelloWorld(cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldResponse> HelloWorldAsync(cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calculersupstraction", ReplyAction="*")]
        double calculersupstraction(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calculersupstraction", ReplyAction="*")]
        System.Threading.Tasks.Task<double> calculersupstractionAsync(double a, double b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : cLIENTwEBSERVICEcSHARP.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<cLIENTwEBSERVICEcSHARP.ServiceReference1.WebService1Soap>, cLIENTwEBSERVICEcSHARP.ServiceReference1.WebService1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldResponse cLIENTwEBSERVICEcSHARP.ServiceReference1.WebService1Soap.HelloWorld(cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequest inValue = new cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequest();
            inValue.Body = new cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequestBody();
            cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldResponse retVal = ((cLIENTwEBSERVICEcSHARP.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldResponse> cLIENTwEBSERVICEcSHARP.ServiceReference1.WebService1Soap.HelloWorldAsync(cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequest inValue = new cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequest();
            inValue.Body = new cLIENTwEBSERVICEcSHARP.ServiceReference1.HelloWorldRequestBody();
            return ((cLIENTwEBSERVICEcSHARP.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public double calculersupstraction(double a, double b) {
            return base.Channel.calculersupstraction(a, b);
        }
        
        public System.Threading.Tasks.Task<double> calculersupstractionAsync(double a, double b) {
            return base.Channel.calculersupstractionAsync(a, b);
        }
    }
}
